POST https://project-nodejs-ne32.onrender.com/videos
Content-Type: application/json

{
    "title": "Denilson Alves",
    "description": "Vai perder pro Rafael F. Souza no MK11",
    "duration": 200
}
###

GET  https://project-nodejs-ne32.onrender.com/videos?search=
Content-Type: application/json

###

PUT  https://project-nodejs-ne32.onrender.com/videos/
Content-Type: application/json

{
    "title": "Denilson Pereira",
    "description": "Minha descrição Pequenininha",
    "duration": 180
}

###
DELETE https://project-nodejs-ne32.onrender.com/videos/